# Generated by Django 4.2.1 on 2023-05-24 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('city', models.CharField(max_length=40)),
                ('state_id', models.CharField(max_length=3)),
                ('state_name', models.CharField(max_length=40)),
                ('zcta', models.BooleanField()),
                ('parent_zcta', models.CharField(blank=True, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('county_fips', models.PositiveIntegerField()),
                ('county_name', models.CharField(max_length=45)),
                ('county_weights', models.JSONField()),
                ('county_names_all', models.CharField(max_length=150)),
                ('county_fips_all', models.CharField(blank=True, max_length=60)),
                ('imprecise', models.BooleanField()),
                ('military', models.BooleanField()),
                ('timezone', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['zip_code'], name='application_zip_cod_170ae9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('delivery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='application.location')),
                ('pick_up', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up', to='application.location')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unic_number', models.CharField(blank=True, max_length=5)),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('current_location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='application.location')),
            ],
        ),
    ]
