# Generated by Django 4.2.1 on 2023-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['current_location'], name='application_current_0fcc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['pick_up'], name='application_pick_up_3717f0_idx'),
        ),
    ]
