# Generated by Django 4.2.1 on 2023-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_car_latitude_car_longitude'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='application_current_0fcc8a_idx',
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['latitude', 'longitude'], name='application_latitud_00702b_idx'),
        ),
    ]
