# Generated by Django 4.2.1 on 2023-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_car_application_current_0fcc8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
