# Generated by Django 4.2.1 on 2023-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_cargo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='unic_number',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
